### ISSUE TITLE
How to upload filesystem image?

### ISSUE THREAD

**Issue by andrico21** [m5stack/AirQUserDemo#4]
Unable to recover demo firmware on a unit: compiled successfully, but README lacks of instruction how to deal with "2. upload filesystem image".

tried to upload using IDE 1.8.19, got positive results in upload, but device isn't working properly - screen just flashing, config webpage won't open with not found error.

**Comment by hpsaturn** [comment]
With PlatformIO is very simple:

`pio run --target uploadfs`

**Comment by nyl162** [comment]
Follow these steps and remember to close Serial Monitor during upload.

https://randomnerdtutorials.com/arduino-ide-2-install-esp32-littlefs/

**Comment by TinyuZhao** [comment]
> Follow these steps and remember to close Serial Monitor during upload.
> 
> https://randomnerdtutorials.com/arduino-ide-2-install-esp32-littlefs/

You are right, for Arduino 1.x version, you can refer to this [tutorial](https://randomnerdtutorials.com/install-esp32-filesystem-uploader-arduino-ide/).
